#!/usr/bin/env python3
"""
 Copyright © François Grabenstaetter <francoisgrabenstaetter@gmail.com>

 This file is part of Digital Assets.

 Digital Assets is free software: you can redistribute it and/or
 modify it under the terms of the GNU General Public License as published
 by the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Digital Assets is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Digital Assets. If not, see <http://www.gnu.org/licenses/>.
"""

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, Gdk, GLib

import platform, sys, gettext

# be sure the package is found
fullVersion = platform.python_version().split('.')
pythonLibDirName = 'python' + str(fullVersion[0] + '.' + fullVersion[1])
moduleParentDirPath = '/usr/lib/' + pythonLibDirName + '/site-packages/'
sys.path.append(moduleParentDirPath)

from DigitalAssets.ui.window import Window
from DigitalAssets.ui.env import *

# set program name
GLib.set_prgname(PROGRAM_NAME)

# init translations
gettext.install('locale', SHARE_PATH + 'locale/')

# create config path if not exists
os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok = True)

Window()
Gtk.main()
